language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
  - pip install . --quiet --use-mirrors
  - pip install pytest nose --quiet --use-mirrors

script: nosetests

branches:
  only:
    - develop
